name: Update Base Docker Image
on:
  workflow_dispatch:
  push:
    tags-ignore:
      - "*"
    branches:
      - main
    paths:
      - 'Dockerfile.base'
      - 'internal/verifier/js/**'
      - 'internal/verifier/php/**'

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    name: Build PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ["8.4", "8.3", "8.2", "8.1"]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # ratchet:step-security/harden-runner@v2.12.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # ratchet:docker/setup-qemu-action@v3

      - name: Login into Github Docker Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # ratchet:docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # ratchet:docker/build-push-action@v6
        with:
          context: .
          push: true
          file: Dockerfile.base
          platforms: linux/amd64,linux/arm64
          tags: "ghcr.io/shopware/shopware-cli-base:${{ matrix.php-version }}"
          build-args: |
            PHP_VERSION=${{ matrix.php-version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
